# 10-Node Localization Demo Configuration
# 4 anchors, 6 unknown nodes in 10x10m area

system:
  seed: 42
  max_iterations: 20
  convergence_threshold: 1e-4

# Hardware assumptions
hardware:
  # RF Front-end
  carrier_freq_ghz: 2.4  # ISM band
  bandwidth_mhz: 100      # 100 MHz bandwidth → 1.5m range resolution
  tx_power_dbm: 20       # 100mW transmit power
  noise_figure_db: 6     # Typical for commercial RF
  
  # Timing hardware
  timestamp_resolution_ns: 10   # MAC/PHY timestamp resolution
  clock_stability_ppm: 10       # Crystal oscillator drift
  allan_deviation: 1e-10        # Fractional frequency stability
  
  # Processing
  sample_rate_msps: 200         # 200 Mega-samples per second
  adc_bits: 12                  # ADC resolution

# Spread spectrum waveform
waveform:
  pn_length: 1023              # Gold code length
  chip_rate_mhz: 100           # Matches bandwidth
  pilot_frequencies_mhz: [-5, -3, -1, 0, 1, 3, 5]
  pilot_power_fraction: 0.3
  ranging_power_fraction: 0.5

# Channel model
channel:
  environment: "indoor"
  path_loss_exponent: 3.0     # Indoor propagation
  nlos_probability: 0.2        # 20% chance of NLOS
  nlos_bias_mean_m: 3.0        # NLOS adds 3m average bias
  nlos_bias_std_m: 1.5         # NLOS bias variation
  multipath_delay_spread_ns: 50

# Node configuration (10x10 meter area)
nodes:
  # Anchors (4 corners)
  - id: 0
    position: [0.0, 0.0]
    is_anchor: true
    name: "Anchor_SW"
    
  - id: 1
    position: [10.0, 0.0]
    is_anchor: true
    name: "Anchor_SE"
    
  - id: 2
    position: [10.0, 10.0]
    is_anchor: true
    name: "Anchor_NE"
    
  - id: 3
    position: [0.0, 10.0]
    is_anchor: true
    name: "Anchor_NW"
    
  # Unknown nodes (6 distributed)
  - id: 4
    position: [2.5, 2.5]
    is_anchor: false
    name: "Node_4"
    
  - id: 5
    position: [7.5, 2.5]
    is_anchor: false
    name: "Node_5"
    
  - id: 6
    position: [5.0, 5.0]
    is_anchor: false
    name: "Node_6_Center"
    
  - id: 7
    position: [2.5, 7.5]
    is_anchor: false
    name: "Node_7"
    
  - id: 8
    position: [7.5, 7.5]
    is_anchor: false
    name: "Node_8"
    
  - id: 9
    position: [5.0, 9.0]
    is_anchor: false
    name: "Node_9"

# Solver configuration
solver:
  algorithm: "levenberg_marquardt"
  huber_delta: 1.0              # Huber loss threshold
  initial_damping: 0.01         # LM damping parameter
  use_quality_weights: true     # Weight by measurement quality
  outlier_threshold: 3.0        # Sigma for outlier detection

# Output configuration
output:
  plot_results: true
  save_trajectory: true
  output_dir: "results/10_node_demo"
  metrics:
    - "rmse"
    - "max_error"
    - "convergence_time"
    - "outlier_percentage"