# 30-Node Large Area Localization Configuration
# 4 anchors, 26 unknown nodes in 50x50m area

system:
  seed: 42
  max_iterations: 100  # More iterations for harder problem
  convergence_threshold: 1e-3

# Hardware assumptions
hardware:
  # RF Front-end
  carrier_freq_ghz: 2.4  # ISM band
  bandwidth_mhz: 100      # 100 MHz bandwidth
  tx_power_dbm: 20       # 100mW transmit power
  noise_figure_db: 6     # Typical for commercial RF

  # Timing hardware
  timestamp_resolution_ns: 10   # MAC/PHY timestamp resolution
  clock_stability_ppm: 10       # Crystal oscillator drift
  allan_deviation: 1e-10        # Fractional frequency stability

  # Processing
  sample_rate_msps: 200         # 200 Mega-samples per second
  adc_bits: 12                  # ADC resolution

# Spread spectrum waveform
waveform:
  pn_length: 1023              # Gold code length
  chip_rate_mhz: 100           # Matches bandwidth
  pilot_frequencies_mhz: [-5, -3, -1, 0, 1, 3, 5]
  pilot_power_fraction: 0.3
  ranging_power_fraction: 0.5

# Channel model (realistic for 50x50m area - mix of indoor/outdoor)
channel:
  environment: "urban"          # More challenging than indoor
  path_loss_exponent: 3.0       # Higher for larger area
  nlos_probability: 0.15        # 15% NLOS (obstacles, walls)
  nlos_bias_mean_m: 2.0         # Larger bias for outdoor
  nlos_bias_std_m: 1.0          # Higher variation
  multipath_delay_spread_ns: 100 # Larger area = more multipath

# Node configuration (50x50 meter area)
nodes:
  # Anchors (4 corners)
  - id: 0
    position: [0.0, 0.0]
    is_anchor: true
    name: "Anchor_SW"

  - id: 1
    position: [50.0, 0.0]
    is_anchor: true
    name: "Anchor_SE"

  - id: 2
    position: [50.0, 50.0]
    is_anchor: true
    name: "Anchor_NE"

  - id: 3
    position: [0.0, 50.0]
    is_anchor: true
    name: "Anchor_NW"

  # Unknown nodes (26 distributed in grid pattern with some randomness)
  - id: 4
    position: [8.0, 8.0]
    is_anchor: false

  - id: 5
    position: [16.0, 8.0]
    is_anchor: false

  - id: 6
    position: [24.0, 8.0]
    is_anchor: false

  - id: 7
    position: [32.0, 8.0]
    is_anchor: false

  - id: 8
    position: [42.0, 8.0]
    is_anchor: false

  - id: 9
    position: [8.0, 16.0]
    is_anchor: false

  - id: 10
    position: [16.0, 16.0]
    is_anchor: false

  - id: 11
    position: [24.0, 16.0]
    is_anchor: false

  - id: 12
    position: [32.0, 16.0]
    is_anchor: false

  - id: 13
    position: [42.0, 16.0]
    is_anchor: false

  - id: 14
    position: [8.0, 25.0]
    is_anchor: false

  - id: 15
    position: [16.0, 25.0]
    is_anchor: false

  - id: 16
    position: [25.0, 25.0]  # Center node
    is_anchor: false

  - id: 17
    position: [34.0, 25.0]
    is_anchor: false

  - id: 18
    position: [42.0, 25.0]
    is_anchor: false

  - id: 19
    position: [8.0, 34.0]
    is_anchor: false

  - id: 20
    position: [16.0, 34.0]
    is_anchor: false

  - id: 21
    position: [24.0, 34.0]
    is_anchor: false

  - id: 22
    position: [32.0, 34.0]
    is_anchor: false

  - id: 23
    position: [42.0, 34.0]
    is_anchor: false

  - id: 24
    position: [8.0, 42.0]
    is_anchor: false

  - id: 25
    position: [16.0, 42.0]
    is_anchor: false

  - id: 26
    position: [24.0, 42.0]
    is_anchor: false

  - id: 27
    position: [32.0, 42.0]
    is_anchor: false

  - id: 28
    position: [42.0, 42.0]
    is_anchor: false

  - id: 29
    position: [25.0, 12.0]
    is_anchor: false

# Solver configuration
solver:
  algorithm: "levenberg_marquardt"
  huber_delta: 2.0              # Larger for more outliers
  initial_damping: 0.01         # LM damping parameter
  use_quality_weights: true     # Weight by measurement quality
  outlier_threshold: 3.0        # Sigma for outlier detection

# Output configuration
output:
  plot_results: true
  save_trajectory: true
  output_dir: "results/30_node_large"
  metrics:
    - "rmse"
    - "max_error"
    - "convergence_time"
    - "outlier_percentage"