# ============================================================================
# ESCAPE LOCAL MINIMA CONFIGURATION
# ============================================================================
# Purpose: Aggressive strategies to escape local minima and find global optimum
# Strategy: Multiple escape mechanisms working together
# 
# Escape Mechanisms:
#   1. Random Perturbation - Add noise when stuck
#   2. Simulated Annealing - Accept worse solutions probabilistically  
#   3. Parameter Shocks - Temporary aggressive parameter changes
#   4. Smart Restart - Restart from perturbed best position
#
# Expected Behavior:
#   - More exploration early on (may see worse intermediate results)
#   - Multiple escape attempts visible in logs
#   - Eventually finds better minimum than standard algorithms
#   - May take more iterations but achieves lower final error
# ============================================================================

extends: stable_convergence.yaml

# ----------------------------------------------------------------------------
# ALGORITHM CONFIGURATION - Aggressive exploration
# ----------------------------------------------------------------------------
algorithm:
  # Start with moderate parameters (will be shocked when stuck)
  gamma: 0.98
  alpha: 5.0
  
  # Enable adaptive features
  adaptive_alpha: true
  
  # More iterations needed for exploration
  max_iterations: 1500
  
  # Don't stop too early - give escape mechanisms time to work
  early_stopping_window: 200

# ----------------------------------------------------------------------------
# ESCAPE MECHANISM CONFIGURATION
# ----------------------------------------------------------------------------
# Random Perturbation
enable_perturbation: true
perturbation_magnitude: 0.05  # Add 5% noise to positions when stuck
stuck_threshold: 50            # Trigger escape after 50 iterations without improvement

# Simulated Annealing
enable_annealing: true
initial_temperature: 1.0       # Start with high temperature (more exploration)
temperature_decay: 0.995       # Slow cooling (T = T * 0.995 each iteration)
                              # After 500 iterations: T ≈ 0.08 (mostly exploitation)

# Parameter Shocking
enable_parameter_shock: true
shock_alpha_multiplier: 3.0   # Temporarily triple alpha when stuck
shock_gamma_reduction: 0.5    # Could also reduce gamma (not implemented yet)
shock_duration: 20            # How long to maintain shocked parameters

# Smart Restart
enable_restart: true
restart_threshold: 150        # Restart if stuck for 150 iterations
restart_perturbation: 0.02    # Add 2% noise to best known position

# ----------------------------------------------------------------------------
# PERFORMANCE MONITORING - Track escape attempts
# ----------------------------------------------------------------------------
performance:
  # More frequent logging to see escape attempts
  log_interval: 5
  
  # Track everything for analysis
  track_metrics: true
  
  # Save more checkpoints to analyze escape behavior
  save_checkpoints: true
  checkpoint_interval: 50

# ----------------------------------------------------------------------------
# OUTPUT CONFIGURATION
# ----------------------------------------------------------------------------
output:
  # Save to dedicated directory for escape experiments
  output_dir: "results/escape_minima/"
  
  # Save intermediate results to track escape attempts
  save_interval: 25
  
  # Generate plots to visualize escape behavior
  plot_results: true