# ============================================================================
# PAPER-EXACT EARLY STOPPING CONFIGURATION
# ============================================================================
# Purpose: Implements the exact early termination criterion from Section 3.2
# "terminate once the last 100 iterations have been higher than 
# the lowest objective value observed to that point"
# 
# Key Finding from Paper:
#   "early termination solution is closer to true locations in 64% of cases"
# ============================================================================

extends: default.yaml

# ----------------------------------------------------------------------------
# ALGORITHM CONFIGURATION - Paper parameters with early stop
# ----------------------------------------------------------------------------
algorithm:
  # Exact paper parameters
  gamma: 0.999
  alpha: 10.0
  
  # Moderate iterations (early stop will kick in)
  max_iterations: 500
  
  # Paper's early stopping criterion
  early_stopping: true
  early_stopping_window: 100  # Paper uses exactly 100 iterations
  
  # No other enhancements - test pure early stopping
  adaptive_alpha: false
  
# ----------------------------------------------------------------------------
# MONITORING - Track when early stop triggers
# ----------------------------------------------------------------------------
performance:
  log_interval: 10
  track_metrics: true
  save_checkpoints: true
  checkpoint_interval: 50

# ----------------------------------------------------------------------------
# OUTPUT CONFIGURATION
# ----------------------------------------------------------------------------
output:
  output_dir: "results/paper_early_stop/"
  save_interval: 25
  plot_results: true