system:
  seed: 42
  max_iterations: 100
  convergence_threshold: 1.0e-06
  verbose: true
hardware:
  timing_precision: ns
  timestamp_resolution_ns: 1.0
  clock_stability_ppm: 20.0
  carrier_freq_ghz: 2.45
  bandwidth_mhz: 200.0
  tx_power_dbm: 20.0
  antenna_gain_dbi: 6.0
  noise_figure_db: 5.0
  sample_rate_msps: 250.0
  adc_bits: 12
network:
  topology: nearest_neighbor
  k_neighbors: 5
  max_neighbor_distance_m: 20.0
  min_rssi_dbm: -80.0
solver:
  algorithm: admm
  huber_delta: 1.0
  rho: 1.0
  use_quality_weights: true
  outlier_threshold: 3.0
  damping: 0.5
nodes:
- id: 0
  position:
  - 0
  - 0
  is_anchor: true
  name: Anchor_0
- id: 1
  position:
  - 10
  - 0
  is_anchor: true
  name: Anchor_1
- id: 2
  position:
  - 5
  - 5
  is_anchor: false
  name: Unknown_2
